# Generated by Django 3.2.19 on 2024-12-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kiss_cache", "0014_auto_resource_url_512"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mirror",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url_pattern",
                    models.CharField(
                        help_text="Regular expression for matching URLs", max_length=255
                    ),
                ),
                ("mirrors", models.TextField(help_text="Ordered list of mirror URLs")),
            ],
        ),
        migrations.AlterField(
            model_name="resource",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
