# Generated by Django 5.1.3 on 2024-11-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kiss_cache", "0014_auto_resource_url_512"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mirror",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url_pattern",
                    models.CharField(
                        help_text="Regular expression for matching URLs", max_length=255
                    ),
                ),
                ("mirrors", models.TextField(help_text="Ordered list of mirror URLs")),
            ],
        ),
    ]
